version: '3.8'

services:

  frontend:
    image: frontend
    ports:
      - 5000

  backend:
    image: backend
    ports:
      - 8080

  proxy:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
