version: '3.5'

services:
  frontend:
    image: frontend
    build: .
    ports:
      - 5000:5000

  backend:
    image: backend
    build: .
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
    
