version: '3.5'

services:

  frontend:
    image: frontend
    build: .
    ports:
      - 5000:5000

  backend:
    image: backend
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
    depends_on:
      - db
  
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

