version: '3.5'

services:

  backend:
    image: backend
    build: .
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    
  redis:
    image: redis
    build: .
    ports:
      - :6379
    